version: '3.8'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: sh -c
    command: >
      "ollama serve & sleep 3 && ollama pull tinyllama && tail -f /dev/null"
volumes:
  ollama_data:
